#   ansible-playbook create_user.yml -i ubuntu@<host>,
---
- name: create user
  hosts: '*'
  become: true
  vars:
  - user: smutch
  vars_prompt:
    - name: password
      prompt: "Enter a password for the new user"

  tasks:
  - name: install zsh
    apt:
      update_cache: yes
      name: zsh
      state: present

  - name: create user
    ansible.builtin.user:
      name: '{{ user }}'
      group: sudo
      password: "{{ password | password_hash('sha512') }}"
      update_password: on_create
      shell: /bin/zsh
    become_user: root

  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: '{{ user }}'
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
