# run with
# ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook dev.yml -K -i <host>, --ssh-common-args='-o ForwardAgent=yes'
---
- name: setup dev debian environment
  hosts: '*'
  roles:
    - common
  vars:
    python: pyenv  # change to system to use apt installed python3 instead
