# run with
# ansible-playbook dev.yml -K -i <host>, --ssh-common-args='-o ForwardAgent=yes'
---
- name: setup dev environment
  hosts: '*'
  roles:
    - common
  vars:
    python: pyenv  # change to system to use apt installed python3 instead
