---
# First ensure you are running from a python env with passlib installed. Then run with:
#   ansible-playbook dev.yml -K -i target_host, --extra-vars '{"user_password": "PASSWORD"}'
- name: setup dev debian environment
  hosts: '*'
  roles:
    - common
