---
- name: gpu-edm
  hosts: '*.unimelb.cloud'
  roles:
    - common

  tasks:
    - name: install CUDA toolkit
      vars:
        - gpu: True
        - cuda_restart_node_on_install: True
      import_role:
        name: CSCfi.cuda
      become: True

    - name: clone spack
      git:
        repo: 'https://github.com/spack/spack.git'
        dest: '~/spack'

    - name: add spack to bashrc
      lineinfile:
        path: '$HOME/.bashrc'
        state: present
        line: '. $HOME/spack/share/spack/setup-env.sh'

    - name: grab the NVIDIA HPC-SDK
      get_url:
        url: https://developer.download.nvidia.com/hpc-sdk/20.9/nvhpc_2020_209_Linux_x86_64_cuda_11.0.tar.gz
        dest: '~/'

    - name: unzip the SDK
      unarchive:
        src: nvhpc_2020_209_Linux_x86_64_cuda_11.0.tar.gz
        dest: '~/'

    - name: install the SDK
      environment:
        NVHPC_SILENT: 1
        NVHPC_INSTALL_DIR: /opt/nvidia/hpc_sdk
        NVHPC_INSTALL_TYPE: single
      shell: '~/nvhpc_2020_209_Linux_x86_64_cuda_11.0/install'
      become: true
      creates: /opt/nvidia/hpc_sdk

    - name: remove the tarball and installer
      file:
        path:
          - '~/nvhpc_2020_209_Linux_x86_64_cuda_11.0.tar.gz'
          - '~/nvhpc_2020_209_Linux_x86_64_cuda_11.0'
        state: absent

    - name: copy the setup script
      copy:
        src: files/setup-nvidia_hpc_sdk.sh
        dest: '~/'
