- name: ronin gpu setup
  hosts: '*.unimelb.cloud'
  roles:
    - role: common
      vars:
        python: pyenv
      tags: common
    - role: ronin_gpu_instance
      vars:
        cuda_type: HPC-SDK
      tags: gpu
