- name: install CUDA toolkit
  import_role:
    name: nvidia.nvidia_driver
  become: true

- name: install the NVIDIA SDK
  apt:
    deb: {{ item }}
  loop:
    - https://developer.download.nvidia.com/hpc-sdk/21.7/nvhpc-21-7_21.7_amd64.deb
    - https://developer.download.nvidia.com/hpc-sdk/21.7/nvhpc-2021_21.7_amd64.deb
    - https://developer.download.nvidia.com/hpc-sdk/21.7/nvhpc-21-7-cuda-multi_21.7_amd64.deb
  become: true
