- name: install CUDA driver
  import_role:
    name: nvidia.nvidia_driver
  become: true

- name: install the NVIDIA HPC SDK
  when: cuda_type == "HPC-SDK"
  block:
  - name: grab the SDK debs
    get_url:
      url: "{{ item }}"
      dest: "{{ ansible_env.HOME }}/"
    loop:
      - https://developer.download.nvidia.com/hpc-sdk/21.7/nvhpc-21-7_21.7_amd64.deb
      - https://developer.download.nvidia.com/hpc-sdk/21.7/nvhpc-2021_21.7_amd64.deb
      - https://developer.download.nvidia.com/hpc-sdk/21.7/nvhpc-21-7-cuda-multi_21.7_amd64.deb

  # N.B. need to do this with a shell command otherwise dependency resolution fails
  - name: install the debs
    shell: >
      apt-get install -y
      ./nvhpc-21-7_21.7_amd64.deb
      ./nvhpc-2021_21.7_amd64.deb
      ./nvhpc-21-7-cuda-multi_21.7_amd64.deb
    become: true

  - name: remove the debs
    ansible.builtin.file:
      path: "{{ ansible_env.HOME }}/{{ item }}"
      state: absent
    loop:
      - nvhpc-21-7_21.7_amd64.deb
      - nvhpc-2021_21.7_amd64.deb
      - nvhpc-21-7-cuda-multi_21.7_amd64.deb

  - name: copy the setup script
    copy:
      src: files/setup-nvidia_hpc_sdk.sh
      dest: "{{ ansible_env.HOME }}/"

- name: install the NVIDIA toolkit
  when: cuda_type == "toolkit"
  become: true
  block:
    - name: grab the pin file
      get_url:
        url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
        dest: "/etc/apt/preferences.d/cuda-repository-pin-600"

    - name: update apt to use cuda repo
      shell: |
        apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
        add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"

    - name: install the toolkit
      apt:
        name: cuda
        state: present
        update_cache: true
