---
- name: import the conda role
  import_role:
    name: evandam.conda

- name: get conda path
  shell: 'find {{ miniconda_parent_dir }}/Miniconda**/bin -name conda -executable'
  register: conda_bin_cmd

- name: store conda_bin fact
  set_fact:
    conda_bin: "{{ conda_bin_cmd.stdout }}"
    setup_conda_env: 'eval "$({{ conda_bin_cmd.stdout }} shell.bash hook 2> /dev/null)"'

- name: create conda env
  conda:
    name: 
    - python
    - jupyterlab
    - black
    - jupyterlab_code_formatter
    - dask
    - dask-labextension
    state: present
    channels: conda-forge
    executable: "{{ conda_bin }}"
    environment: "{{ jupyter_conda_env }}"

- name: enable jupyterlab extensions
  script: "../files/jupyterlab_extension.sh {{ conda_bin }} {{ jupyter_conda_env }}"
