---
- name: get conda path
  shell: 'find {{ miniconda_parent_dir }}/Miniconda**/bin -name conda -executable'
  register: conda_bin_cmd

- name: store conda_bin fact
  set_fact:
    conda_bin: "{{ conda_bin_cmd.stdout }}"
    setup_conda_env: 'eval "$({{ conda_bin_cmd.stdout }} shell.bash hook 2> /dev/null)"'

- name: create conda env
  import_role:
    name: andrewrothstein.conda-env
  vars:
    conda_env_name: "{{ jupyter_conda_env }}"
    conda_env_environment: "jupyter-env.yml"

- name: enable jupyterlab extensions
  become: true
  script: "../files/jupyterlab_extension.sh {{ conda_bin }} {{ jupyter_conda_env }}"
