---
- name: neovim
  include_tasks: neovim.yml

- name: miniconda
  include_tasks: miniconda.yml

- name: tmux
  include_tasks: tmux.yml

- name: starship
  include_tasks: starship.yml

- name: bash aliases
  copy:
    src: '../files/bash_aliases'
    dest: ~/.bash_aliases

- name: gitconfig
  copy:
    src: '../files/gitconfig'
    dest: ~/.gitconfig

