---
- name: neovim
  include_tasks: neovim.yml

- name: tmux
  include_tasks: tmux.yml

- name: starship
  tasks:
    shell: 'curl -fsSL https://starship.rs/install.sh | bash -s -- -y 
      && starship init bash >> .bashrc'
    args:
      creates: /usr/local/bin/starship
    become: true
  tasks:
    copy:
      src: '../files/starship.toml'
      dest: '~/.config/starship.toml'

- name: bash aliases
  copy:
    src: '../files/bash_aliases'
    dest: ~/.bash_aliases

- name: miniconda
  import_role:
    name: andrewrothstein.miniconda
