- name: generate locale
  shell:
    cmd: locale-gen en_AU.UTF-8
  become: true

- name: copy ghostty terminfo
  shell:
    cmd: tic -x -
    stdin: "{{ lookup('pipe', 'infocmp -x ghostty') }}"

- name: install zsh
  apt:
    name: zsh
    state: present
    update_cache: true
  become: true

- name: download dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:smutch/dotfiles.git'
    dest: '{{ ansible_env.HOME }}/dotfiles'
    accept_hostkey: true

- name: install dotfiles
  shell:
    chdir: '{{ ansible_env.HOME }}/dotfiles'
    cmd: ./install linux
    executable: /bin/zsh

- name: install UV
  shell: |
    curl -LsSf https://astral.sh/uv/install.sh | sh -s -- -q
  args:
    creates: '{{ ansible_env.HOME }}/.local/bin/uv'
