- name: generate locale
  shell:
    cmd: locale-gen en_AU.UTF-8
  become: true

- name: download dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:smutch/dotfiles.git'
    dest: '{{ ansible_env.HOME }}/dotfiles'

- name: install dotfiles
  shell:
    chdir: '{{ ansible_env.HOME }}/dotfiles'
    cmd: ./install linux
    executable: /bin/zsh

- name: install tmux
  apt:
    name: tmux
    state: present
    update_cache: true
  become: true

- name: setup python
  include_tasks: python.yml

- name: install neovim
  include_tasks: neovim.yml
