---
- name: create bin directory
  file:
    path: ~/bin
    state: directory

- name: download neovim
  get_url:
    url: https://github.com/neovim/neovim/releases/download/latest/nvim.appimage
    dest: ~/bin/nvim
    mode: '750'

# PYENV =============

- name: get the pyenv global pip location
  shell: '{{ ansible_env.HOME }}/.pyenv/bin/pyenv which pip'
  register: pip_command
  ignore_errors: true
  when: python == "pyenv"

- name: install pynvim in the pyenv global python
  pip:
    executable: '{{ pip_command.stdout }}'
    name: pynvim
  when: python == "pyenv"

# OR SYSTEM PYTHON

- name: install pynvim
  pip:
    executable: 'pip3'
    name: pynvim
  when: python == "system"

# ===================

- name: install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: install nodejs via nvm
  shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install node"
  args:
    executable: /bin/bash
