---
- name: create bin directory
  file:
    path: ~/bin
    state: directory

- name: download neovim
  get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: ~/bin/nvim
    mode: '750'

- name: create config directory
  file:
    path: ~/.config
    state: directory

- name: clone neovim config
  git:
    repo: 'https://github.com/smutch/vim-config.git'
    dest: ~/.config/nvim
    version: master

- name: add system options
  copy:
    src: '../files/system.vim'
    dest: '~/.config/nvim/system.vim'
  
- name: ensure python3 installed
  become: true
  apt:
    update_cache: yes
    name:
      - python3
      - python3-pip
    state: present

- name: install pynvim globally
  become: true
  pip:
    executable: pip3
    name: pynvim

- name: install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: install nodejs via nvm
  shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install node"
  args:
    executable: /bin/bash

- name: install pyright lang server
  shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && npm install -g pyright"
  args:
    executable: /bin/bash

- name: setup neovim
  shell: '~/bin/nvim -u ~/.config/nvim/plugins.vim +PlugInstall +qall'
