---
# PYENV =============

- name: install pynvim in the pyenv global python
  pip:
    executable: '{{ pip_command.stdout }}'
    name: pynvim
  when: python == "pyenv"

# OR SYSTEM PYTHON

- name: install pynvim
  pip:
    executable: 'pip3'
    name: pynvim
  when: python == "system"

# ===================

# - name: install nvm
#   shell: >
#     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
#   args:
#     creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

# - name: install nodejs via nvm
#   shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install node"
#   args:
#     executable: /bin/bash
