# PYENV =============
- name: install pyenv, pyenv-virtualenv
  shell: |
    curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | zsh
  args:
    creates: '{{ ansible_env.HOME }}/.pyenv'
  when: python == "pyenv"

- name: install requirements to build python
  apt:
    name:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev 
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    state: present
    update_cache: true
  become: true
  when: python == "pyenv"

- name: install python 3.11 (may take some time) and set to global
  shell: >
    {{ ansible_env.HOME }}/.pyenv/bin/pyenv install -s 3.11 &&
    {{ ansible_env.HOME }}/.pyenv/bin/pyenv global 3.11
  when: python == "pyenv"

# OR SYSTEM PYTHON

- name: install pip
  apt:
    name: python3-pip
  become: true
  when: python == "system"

# ===================

- name: get the pyenv global pip location
  shell: '{{ ansible_env.HOME }}/.pyenv/bin/pyenv which pip'
  register: pip_command
  ignore_errors: true
  when: python == "pyenv"

- name: install pipx
  pip:
    executable: '{{ pip_command.stdout }}'
    name: pipx

- name: pipx ensurepath
  shell: >
    {{ ansible_env.HOME }}/.pyenv/bin/pyenv exec pipx ensurepath
  args:
    executable: /bin/zsh

- name: install poetry and hatch
  shell: >
    # source {{ ansible_env.HOME }}/.zprofile
    pipx install poetry hatch
  args:
    executable: /bin/zsh

- name: install mambaforge
  shell: |
    curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p {{ mambaforge_dir }} && rm Mambaforge-$(uname)-$(uname -m).sh
  args:
    executable: /bin/zsh
    creates: '{{ mambaforge_dir }}'

- name: add mambaforge to zshrc
  shell: '{{ mambaforge_dir }}/bin/mamba init zsh'
  args:
    executable: /bin/zsh
