---
- name: install starship
  shell: 'curl -fsSL https://starship.rs/install.sh | bash -s -- -b /home/ubuntu/bin -y'
  args:
    creates: ~/bin/starship

- name: update bashrc
  shell: '/home/ubuntu/bin/starship init bash >> .bashrc'

- name: upload starship config
  copy:
    src: '../files/starship.toml'
    dest: '~/.config/starship.toml'
